CREATE DATABASE IF NOT EXISTS ASSURAUTO;
USE ASSURAUTO;

CREATE TABLE IF NOT EXISTS CLIENTS(
	CL_ID INT NOT NULL PRIMARY KEY,
	CL_NOM VARCHAR(20) NOT NULL,
    CL_PRENOM VARCHAR(20) NOT NULL,
    CL_ADRESSE VARCHAR(40) NOT NULL,
    CL_CODEPOSTAL INT(5) NOT NULL check ('06400'),
    CL_VILLE VARCHAR(30) NOT NULL check('Cannes'),
    CL_TEL VARCHAR(15) NOT NULL,
    CL_FAX VARCHAR(15) NOT NULL,
    CL_MAIL VARCHAR(40) NOT NULL
    );
  
CREATE TABLE IF NOT EXISTS CONTRAT (
	CO_ID INT NOT NULL PRIMARY KEY,
    CO_DATE DATE NOT NULL,
    CO_CATEGORIE CHAR(20) ,
    CO_BONUS FLOAT NOT NULL DEFAULT 0,
    CO_MALUS FLOAT NOT NULL DEFAULT 0,
    CO_CLIENTS_FK INT NOT NULL,
    FOREIGN KEY (CO_CLIENTS_FK) REFERENCES CLIENTS(CL_ID)
    );

INSERT INTO CLIENTS(CL_ID,CL_NOM,CL_PRENOM,CL_ADRESSE,CL_CODEPOSTAL,CL_VILLE,CL_TEL,CL_FAX,CL_MAIL) VALUES
(564,'CANCIAN','HADRIEN','1459 CH DE CARIMAÏ','06250','MOUGINS','0618194839','0000000000','hadriencancian@gmail.com');

INSERT INTO CONTRAT(CO_ID,CO_DATE,CO_CATEGORIE,CO_BONUS,CO_MALUS,CO_CLIENTS_FK) VALUES
(58,'1997-01-01','TIERS',0,0,40);

SELECT * FROM CLIENTS;
SELECT * FROM CONTRAT;